name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Force an error
        run: exit 1
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && ! contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
      - name: Send Discord notification
        if: ${{ github.event_name == 'push' && ! contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: "✅ Deployment Successful! A new version deployed to production"
          title: "Deployment Details"
          description: |
            **Commit:** ${{ github.event.head_commit.id }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
          color: 0x0000ff
          url: ${{ github.event.head_commit.url }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && ! contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  notify_failure:
    needs: [simple_deployment_pipeline]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification (push)
        if: ${{ github.event_name == 'push')
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          content: "❌ Build Failed! The pipeline encountered an error"
          title: "Failure Details"
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha}}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ github.job }}

            [View Commit](${{ github.event.head_commit.url }})
            [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          color: 0xf44336
      - name: Send Discord notification (pull request)
        if: ${{ github.event_name == 'pull_request')
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "❌ Build Failed! The pipeline encountered an error"
          title: "Failure Details"
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.head_ref }}
            **Commit:** ${{ github.event.after}}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ github.job }}

            [View Commit](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.after }})
            [View Workflow](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          color: 0xf44336
